<?php

use Illuminate\Database\Seeder;

class PemasukanPengeluaranSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	$users = \App\User::all();
    	$date = range(1, date('t'));
    	foreach ($users as $user) {
    		$data = [
    			[
    				'nama_item'		=> 'Stop Kontak Arde 5 Lubang + Kabel 3 Meter & Saklar Sunfree Jupiter 35 FS-16Z',
    				'jenis'			=> 'pengeluaran',
    				'kategori'		=> 'Marketplace',
    				'nominal'		=> 33000,
    				'tanggal'		=> '2019-10-10',
    				'tempat'		=> 'Shopee',
    				'deskripsi'		=> '10.10',
    				'user_id'		=> $user->id,
    			],
    			[
    				'nama_item'		=> 'Usb Hub Saklar 4 Port On/Off High speed',
    				'jenis'			=> 'pengeluaran',
    				'kategori'		=> 'Marketplace',
    				'nominal'		=> 27195,
    				'tanggal'		=> '2019-10-10',
    				'tempat'		=> 'Shopee',
    				'deskripsi'		=> '10.10',
    				'user_id'		=> $user->id,
    			],
    			[
    				'nama_item'		=> 'Gaming Mouse Pad XL Desk Mat Motif Peta Dunia 300 x 800 mm',
    				'jenis'			=> 'pengeluaran',
    				'kategori'		=> 'Marketplace',
    				'nominal'		=> 26900,
    				'tanggal'		=> '2019-10-10',
    				'tempat'		=> 'Shopee',
    				'deskripsi'		=> '10.10',
    				'user_id'		=> $user->id,
    			],
    			[
    				'nama_item'		=> 'TERLARIS-Termos Karakter Stainless Steel Logo Mickey Mouse-TERMURAH [Biru]',
    				'jenis'			=> 'pengeluaran',
    				'kategori'		=> 'Marketplace',
    				'nominal'		=> 25863,
    				'tanggal'		=> '2019-10-10',
    				'tempat'		=> 'Shopee',
    				'deskripsi'		=> '10.10',
    				'user_id'		=> $user->id,
    			],
    			[
    				'nama_item'		=> 'Mouse Gaming Armaggeddon Scorpion 7 Free Mousematt - Garansi Resmi 2 Tahun - Product Of Singapore',
    				'jenis'			=> 'pengeluaran',
    				'kategori'		=> 'Marketplace',
    				'nominal'		=> 84000,
    				'tanggal'		=> '2019-10-10',
    				'tempat'		=> 'Lazada',
    				'deskripsi'		=> '10.10',
    				'user_id'		=> $user->id,
    			],
    			[
    				'nama_item'		=> 'HEADSET GAMING NYK RGB HS-P10',
    				'jenis'			=> 'pengeluaran',
    				'kategori'		=> 'Marketplace',
    				'nominal'		=> 226250,
    				'tanggal'		=> '2019-10-10',
    				'tempat'		=> 'Lazada',
    				'deskripsi'		=> '10.10',
    				'user_id'		=> $user->id,
    			],
    			[
    				'nama_item'		=> 'Float dark chocolate',
    				'jenis'			=> 'pengeluaran',
    				'kategori'		=> 'Makanan',
    				'nominal'		=> 8250,
    				'tanggal'		=> '2019-10-10',
    				'tempat'		=> 'Burger King',
    				'deskripsi'		=> 'promo sampai 31 november',
    				'user_id'		=> $user->id,
    			],
    			[
    				'nama_item'		=> 'Kentang plus es krim plus soda',
    				'jenis'			=> 'pengeluaran',
    				'kategori'		=> 'Makanan dan Minuman',
    				'nominal'		=> 15000,
    				'tanggal'		=> '2019-10-10',
    				'tempat'		=> 'Burger King',
    				'deskripsi'		=> 'promo sampai 31 november',
    				'user_id'		=> $user->id,
    			],
    			[
    				'nama_item'		=> 'Bensin Pertalite',
    				'jenis'			=> 'pengeluaran',
    				'kategori'		=> 'Kendaraan',
    				'nominal'		=> 8000,
    				'tanggal'		=> '2019-10-10',
    				'tempat'		=> 'POM Trunojoyo',
    				'deskripsi'		=> null,
    				'user_id'		=> $user->id,
    			],
    			[
    				'nama_item'		=> 'Nasi nugget nila squash',
    				'jenis'			=> 'pengeluaran',
    				'kategori'		=> 'Makanan dan Minuman',
    				'nominal'		=> 21000,
    				'tanggal'		=> '2019-10-10',
    				'tempat'		=> 'Mbak Vivi',
    				'deskripsi'		=> null,
    				'user_id'		=> $user->id,
    			],
    			[
    				'nama_item'		=> 'Nasi tahu mie tongkol',
    				'jenis'			=> 'pengeluaran',
    				'kategori'		=> 'Makanan',
    				'nominal'		=> 8000,
    				'tanggal'		=> '2019-10-10',
    				'tempat'		=> 'Warung Merah Jawa 7',
    				'deskripsi'		=> null,
    				'user_id'		=> $user->id,
    			],
    			[
    				'nama_item'		=> 'Celana Hitam',
    				'jenis'			=> 'pengeluaran',
    				'kategori'		=> 'Makanan',
    				'nominal'		=> 91000,
    				'tanggal'		=> '2019-10-10',
    				'tempat'		=> 'Roxy Square Jember',
    				'deskripsi'		=> null,
    				'user_id'		=> $user->id,
    			],


    			[
    				'nama_item'		=> 'Nasi Jagung',
    				'jenis'			=> 'pengeluaran',
    				'kategori'		=> 'Makanan',
    				'nominal'		=> 8000,
    				'tanggal'		=> '2019-10-13',
    				'tempat'		=> 'Jalan Bangka',
    				'deskripsi'		=> null,
    				'user_id'		=> $user->id,
    			],
    			[
    				'nama_item'		=> 'Charger Lenovo IP 110',
    				'jenis'			=> 'pengeluaran',
    				'kategori'		=> 'Marketplace',
    				'nominal'		=> 108850,
    				'tanggal'		=> '2019-10-13',
    				'tempat'		=> 'Shopee',
    				'deskripsi'		=> null,
    				'user_id'		=> $user->id,
    			],
    			[
    				'nama_item'		=> 'Pasta gigi, sunlight, sabun dettol',
    				'jenis'			=> 'pengeluaran',
    				'kategori'		=> 'Peralatan Mandi',
    				'nominal'		=> 34700,
    				'tanggal'		=> '2019-10-13',
    				'tempat'		=> 'Alfamart',
    				'deskripsi'		=> null,
    				'user_id'		=> $user->id,
    			],
    			[
    				'nama_item'		=> 'Pisang, Indomie goreng, smoothies',
    				'jenis'			=> 'pengeluaran',
    				'kategori'		=> 'Ngafe',
    				'nominal'		=> 30000,
    				'tanggal'		=> '2019-10-12',
    				'tempat'		=> 'Kafe Armor',
    				'deskripsi'		=> null,
    				'user_id'		=> $user->id,
    			],
    			[
    				'nama_item'		=> 'Nasi goreng telur',
    				'jenis'			=> 'pengeluaran',
    				'kategori'		=> 'Makanan',
    				'nominal'		=> 8000,
    				'tanggal'		=> '2019-10-11',
    				'tempat'		=> 'Depan Indomaret, Riau',
    				'deskripsi'		=> null,
    				'user_id'		=> $user->id,
    			],
    			[
    				'nama_item'		=> 'Air mineral dan frestea',
    				'jenis'			=> 'pengeluaran',
    				'kategori'		=> 'Minuman',
    				'nominal'		=> 5000,
    				'tanggal'		=> '2019-10-11',
    				'tempat'		=> 'Alfamart',
    				'deskripsi'		=> null,
    				'user_id'		=> $user->id,
    			],
    			[
    				'nama_item'		=> 'Nasi tongkol merah plus tahu',
    				'jenis'			=> 'pengeluaran',
    				'kategori'		=> 'Makanan',
    				'nominal'		=> 8000,
    				'tanggal'		=> '2019-10-11',
    				'tempat'		=> 'Warung Merah Jawa 7',
    				'deskripsi'		=> null,
    				'user_id'		=> $user->id,
    			],
    			[
    				'nama_item'		=> 'Soto ayam dan es teler strawberry',
    				'jenis'			=> 'pengeluaran',
    				'kategori'		=> 'Makanan dan Minuman',
    				'nominal'		=> 20000,
    				'tanggal'		=> '2019-10-11',
    				'tempat'		=> 'Ikiwawa Tidar',
    				'deskripsi'		=> null,
    				'user_id'		=> $user->id,
    			],
    			[
    				'nama_item'		=> '2 Ayam bakar plus 2 air jeruk ',
    				'jenis'			=> 'pengeluaran',
    				'kategori'		=> 'Makanan dan Minuman',
    				'nominal'		=> 26000,
    				'tanggal'		=> '2019-10-12',
    				'tempat'		=> 'Mbak Vivi',
    				'deskripsi'		=> null,
    				'user_id'		=> $user->id,
    			],
    		];
    		DB::table('pemasukan_pengeluaran')->insert($data);
    	}
    }
}
